---
name: Lint Code Base

on: push

jobs:
    super-lint:
        name: Lint Code Base
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Investigation 1
              run: ls -asl

            - name: Investigation 2
              run: ls -asl "$GITHUB_WORKSPACE"

            - name: Investigation 3
              run: echo "$GITHUB_WORKSPACE"

            - name: Lint Code Base
              uses: github/super-linter@v4
              env:
                  VALIDATE_YAML: false
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  LINTER_RULES_PATH: /
